### ISSUE TITLE
Seperate the bvp from ivp solver

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#10]
This is one we might need a vote on. Should we have separate libraries for ivp's and bvp's? I say yes since bvp solvers are essentially just repeated ivp solvers.

**Comment by SeanMatthewNolan** [comment]
I think we should separate them. That way we can use different ones within a single bvp method and use them elsewhere. An example of separate libraries being useful is to have a regular ivp and a stiff ivp solver and have an option to switch them. This will be cleaner and more flexible across several methods separating the libraries.

**Comment by msparapa** [comment]
gotcha. I'm going to drop in the ivpsol package from my other repository so I got this.
