### ISSUE TITLE
Speed up bc func calls

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#104]
In removing pystache in #102, I had to call some `exec()` commands to properly evaluate the boundary conditions. This is done every time the boundary condition function is called. I'm seeing a minor slowdown in shooting methods, but a pretty major slowdown in collocation. This issue stems from a larger issue upstream, in my opinion, from `optimlib` where the boundary conditions take `x_0` and send it to `_x0['x']` as a string, where it assumes the boundary condition function will use a dictionary formatted the same way.

**Comment by msparapa** [comment]
@SeanMatthewNolan I need your input on this. In the latest I104 branch, I removed "initial" and "terminal" values and the solver internally handles everything as constants. I did this since you'll see in the master branch, in `codegen.py`, I use the `exec()` function a lot because initial and terminal points come in as dictionary values. We don't know what the dictionary call is prior to generating the boundary condition function so that was my short term workaround. My fix to this workaround for the "traditional" method is in I104. Before I fix the "icrm" method for this, I want your input.

What was changed:
- All initial and terminal constraint values are now simply just "constants", or "const" in the continuation

Pros:
✔️ Boundary conditions are more generalized. Since adjoined method is always used at very little computational cost, modifying a constant that appears in the boundary conditions is much more straightforward. This gets even better when you start to think about scaling, since the user will explicitly define units with the constants.
✔️ Boundary conditions are compiled using the same functions as the eoms. They use `njit()` now.
✔️ Because functions are reused, there's less clutter overall. It will be easier to write test cases. There will be less errors moving forward.

Cons:
⛔️ Prior to solving the very first iteration, the solver searches the names of the constants to see if any have the same names as the states with the "_0" or "_f" appended. Then it switches out the original value with what was propagated in the initial guess. Functionally, this makes the solver in branch I104 the exact same as master. I can't really think of a good way to tell a user this is happening or a better way to implement this at the moment.

**Comment by SeanMatthewNolan** [comment]
@msparapa I actually thought of doing nearly the exact same thing so I am for it. I was never a fan of the `'y - y_f`' thing because it isn't clear what y_f was, etc. How propagating the guess is handled does seem like the only issue, but maybe we can have it solve for the initial constant location or have a method within guess such as `.set('c', 'y', 'terminal')'`.

**Comment by msparapa** [comment]
Alright I've implemented it. You'll need to adjust the input files for any problems that use the old format. I'll make a new issue soon on handling the start condition better.
