### ISSUE TITLE
Remove unadjoined method?

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#109]
Now that #47 is implemented, the adjoined and non-adjoined methods are fairly close to one another in terms of performance. I don't see any particular case where using the non-adjoined method would be preferred over the adjoined method. Should we remove the designer's ability to choose and always use the adjoined method?

Normally I would say no when it comes to removing features, but internally, the non-adjoined method is fairly clunky and one extra feature we need to maintain. It's clunky because it requires a few steps of hard-coding, whereas using the adjoined method is generalized. Because of this, I say yes, remove it. Thoughts @SeanMatthewNolan? Should we consult Prof Grant about this one?

**Comment by SeanMatthewNolan** [comment]
I am fine with removing it. I agree it doesn't seem worth maintaining. The adjoined method always seemed more elegant to me anyways.
