### ISSUE TITLE
Find a better method for handling adjustments of constants based on initial guess

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#113]
Continuing from #104, the way our solver handles constants now is if there is a constant with the same name as a state with `_0` or `_f` appended, it will modify the constant after the initial guess but prior to the very first bvp iteration. This happens regardless of whether or not the constant will appear in the continuation process that follows.

```
states: x, y, z
x_f = 0 set by user
<initial guess>
x_f = 0.015 or something random set by the solver
<bvp continuation 1>
x_f = 0.1
<bvp continuation 2>
etc...
```

This feature is required for problems to converge on their very first step, but it is fairly unclear and I can't think of a better way to implement this at the moment. We'll need to brainstorm a better way of handling this, or at least a better method of providing feedback to the user that this is happening.

**Comment by SeanMatthewNolan** [comment]
In theory yes, but I think that may just result in a singular matrix.
