### ISSUE TITLE
Costate guess needs to be specified explicitly to contain coparameter guess for guess generator to work

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#130]
When generating an initial guess, the keyword argument `costate_guess` needs to be a list of costate guesses than coparameter guesses. This is because the guess generator doesn't know how many parameters are in the problem.

**Comment by msparapa** [comment]
I'm not entirely sure how relevant this is. Let's hold off until after I implement what I mentioned in my email from earlier.

**Comment by SeanMatthewNolan** [comment]
I'm closing this because this was changed when the coparameters were included with quads.
