### ISSUE TITLE
Debug option for logging should output more information

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#131]
Using the debug option used to output the derived necessary conditions as well as show progress of the solver during steps (i.e. showing current residual). I found these very helpful. I don't think showing these should be default but is appropriate for the debug option.

**Comment by msparapa** [comment]
I added a debug print statement for the entire `optimlib` output. It should return almost entirely strings anyways so it should work out for whatever future changes are made. I think this is the big one you wanted. You can add other debug print statements as you see fit directly to master.

**Comment by SeanMatthewNolan** [comment]
I finished adding everything that I wanted, so I'll close the issue. I apologize for not doing it previously. I didn't realize that I was using the wrong argument for `add_logger`.
