### ISSUE TITLE
Check for Armijo step becoming too small placed in wrong location 

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#132]
This check was placed in the wrong while loop causing the solver to break if the step length got to small because to root solver would stop prematurely.

**Comment by msparapa** [comment]
This was my fault, twice in a row. I couldn't seem to get this right. 😞 I lowered the minimum `ll` value from 0.1 to 0.05 because brachistochrone was failing a bunch. Really brachisto just doesn't have a great initial guess, but thats a more difficult problem. Should be good to go now.
