### ISSUE TITLE
Bisection strategy does not function

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#134]
When the shooting method fails (at least with the error exceeds `max_error`), a bisection does not occur. Instead the solver just exits.

**Comment by SeanMatthewNolan** [comment]
The bisection strategy works sometimes. I don't know why.

**Comment by msparapa** [comment]
If the first iteration in a continuation doesn't converge, bisection won't retry if it fails. If it's the second or third or later on, then it should retry with a smaller step. I think this is correct behavior. I don't recall who programmed this.

**Comment by SeanMatthewNolan** [comment]
I know that. It was quitting on the second step though. I've also had it quit after the second step too.

**Comment by SeanMatthewNolan** [comment]
In the first step it exits because there is nothing to bisect. Thomas programmed it.

**Comment by msparapa** [comment]
Huh weird. We probably just need to go through the entire module in detail sometime.

**Comment by SeanMatthewNolan** [comment]
Agreed, I think it has to do with exception handling.

**Comment by SeanMatthewNolan** [comment]
I haven't run into this issue in a while. I think it was a matter of running into the wrong type of exception. I think we should close insofar as I don't think I can recreate the problem anymore. If it does occur again, a more specific issue should be made.
