### ISSUE TITLE
Replace current handling of custom functions with tools from SymPy's Functions module

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#137]
Some neat tools listed [here](https://docs.sympy.org/latest/modules/functions/index.html). This should help me in integrating custom functions with the diffy g optimization library. Overall it seems like a better method of handling the custom functions. The codegen module should then be responsible for switching out derivatives of custom SymPy functions with either numerical or automatic differentiated actual functions. We could even allow user to supply their own derivatives.

**Comment by SeanMatthewNolan** [comment]
With this too, we may want to add some of our own functions that SymPy can recognize. For example, I've been using Harish's RASHS stuff, and it would be helpful to have a built in sigmoid function in the solver that can be written to avoid potential overflow in the denominator and be be easier to use.

**Comment by msparapa** [comment]
We'll need a slightly more general solution here. Making custom functions in SymPy is relatively easy. Finding and replacing these functions and their 1st and 2nd derivatives is the tricky part. I think the main contribution on this task will be how we handle the output derivatives.

**Comment by msparapa** [comment]
@SeanMatthewNolan There's no more goofy hardcoded finite differences in our solver any more. Yay! Instead, `sympify` automatically makes sympy Functions out of the unknown custom functions. Then it passes through optimlib as a usual sympy function, and it's now codegen's responsibility to correctly calculate the derivatives. It does this using autograd, which doesn't like integer outputs. So see how I modified Zermelo's problem to output `0.0` instead of `0` for the drift in x. Doing AD on zermelo's actually slowed the problem way down, but we could build in a feature where the 4th argument in custom_function specifies user-defined derivatives and then codegen forgoes autograd altogether.

You'll need to rerun the pip install to install autograd if you don't have it already.
