### ISSUE TITLE
Get parallelization working again on multiple shooting

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#17]

**Comment by SeanMatthewNolan** [comment]
Does the solver now not use multiple shooting at all? I generally use more arcs for stability more than speed and that doesn't appear to be an option.

**Comment by msparapa** [comment]
Nah we don't have it right now. I was going to integrate it all into a single `shooting` object but got distracted by path constraints. I'll try to add this in later this week or next.

**Comment by msparapa** [comment]
I cranked `num_arcs` up to 6 and was able to get the correct solution on brachistochrone so multiple shooting should work for stability purposes. I'll need to think a little bit more on how the parameters show up in the jacobian matrix since, right now, each individual arc contributes to the parameter columns by summation. There's probably a smarter way to do this though. Also parallelization is going to still take quite a bit of work. Some data is lost when spawning new processes so we'll need to rework the code compiling module for that.

**Comment by SeanMatthewNolan** [comment]
I think I have the form of the Jacobian wrt parameters worked out for my own solver, so after I get it coded and tested, I can let you know how I did it.

**Comment by SeanMatthewNolan** [comment]
@msparapa I have fully functioning parallel multiple shooting code written in a custom solver that works pretty well. I won't be able to get to it for a number of weeks, but I would be happy to get it working if you don't have the bandwidth. I feel fairly comfortable with the multiprocessing package now.

**Comment by msparapa** [comment]
Sweet! You'll see my sad attempt at adding multiple shooting on lines 300-334 in `Shooting()`. I ran into an issue where some of the data buried within the ode and bc funcs weren't making their way into the other processes. So the issue is upstream, I think in the codegen module and deals with the template functions in optimlib. Somehow the functions are "loosing" other functions defined within the same scope.

**Comment by msparapa** [comment]
Also parallelization isn't a huge deal for me at the moment. If we don't get it for a few months, then no big deal.

**Comment by SeanMatthewNolan** [comment]
I have been working on getting this working, but run into issues with the module created to hold the generated code. Is there any reason why this code isn't just stored as functions within the problem or other object instead of generating a module?

**Comment by msparapa** [comment]
I'm not entirely sure. My guess is that it's an issue caused by how we compile functions because I believe that's what stopped me before. I don't know what the advantage of using a code module over regular functions is.

**Comment by SeanMatthewNolan** [comment]
@msparapa If it's ok with you, I'll attempt to store them in an object like what seems more normal.

**Comment by msparapa** [comment]
Sure. Make a branch that only focuses on getting parallelization working. I know it's a pain to get working, I've tried and failed ~3-4 times this year so far. We can focus on how it "looks" after there's a working prototype.

**Comment by SeanMatthewNolan** [comment]
Ok, for the record, I wrote a solver that handles parallelization well, so I am mostly trying to replicate that.
