### ISSUE TITLE
Remove collocation folder from beluga/bvpsol

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#174]
This folder seems out of place and the 3 short methods probably should be in Collocation.py. @msparapa If there is an objection, let me know. Otherwise, I'll make the change.

**Comment by msparapa** [comment]
Eeeehhh.... I was starting to separate out functions I knew worked and was planning on cythonizing them. Once files are cythonized, they drop compiled files next to them so this was me planning ahead on organization if we ever decided to compile functions.

But as it stands right now, you're right they don't really make sense.

**Comment by SeanMatthewNolan** [comment]
Oh, what should I do with them then? I'd suggest moving them into Collocation.py with a `TODO cythonize` comment. Then, when/if they are cythonized, we move them into a cythonized folder probably with subdirectory like `cythonized\collocation\ ...`.

**Comment by msparapa** [comment]
Yeah let's move them back into the collocation.py file for now. We can deal with it later once we start using cython.
