### ISSUE TITLE
Add Goddard Rocket example

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#180]
Not really an issue, but I like referencing something.

**Comment by msparapa** [comment]
I actually think I just solved this problem. Or rather the reverse of the problem. See 9-moonlander. You should still implement your solution with epsilon-trig because I used UTM + ICRM.

**Comment by SeanMatthewNolan** [comment]
That's a good problem and solution. The problem is pretty similar, but somewhat different from the Goddard rocket.

**Comment by SeanMatthewNolan** [comment]
@msparapa We can easily use this example as a comparison to pseudospectral methods. We obtain a higher quality solution in a fraction of the time.

**Comment by msparapa** [comment]
Best comparison right now would be against opengoddard's solution. Pseudospectral still uses my slow npnlp package.

**Comment by SeanMatthewNolan** [comment]
That was the comparison I was talking about

**Comment by msparapa** [comment]
Between time 0.025 and 0.075, is the control on a singular arc? I'm not too certain what's going on here. Making epsilon not so small kind of reveals a bit more about what the control is doing.

**Comment by SeanMatthewNolan** [comment]
Oh, I was adding the plots last night. I just didn't get a chance to push them. In this case, the control should be bang-bang. As epsilon goes to 0, it mathematically will converge to the original problem.

**Comment by msparapa** [comment]
BOCOP seems to think that, unconstrained (black line in plot below), there's a singular arc between 0.025 and 0.075. With really small epsilon for us, it appears as if the thrust is off between 0.025 and 0.075, but velocity is increasing albeit increasing slower than <0.025.

Looking at opengoddard's solution, it sorta resolved this same shape as well, but not nearly as smooth.

![control](https://user-images.githubusercontent.com/9142820/56460675-7ada6500-6374-11e9-8984-0a8f25d6ffee.png)

**Comment by SeanMatthewNolan** [comment]
That problem has a dynamic pressure constraint. I was actually going to add that as a variation in that folder. It's described in this article: https://arc-aiaa-org.ezproxy.lib.purdue.edu/doi/pdf/10.2514/3.21080

**Comment by SeanMatthewNolan** [comment]
As long as the problem solves, the epsilon should be as small as possible.

**Comment by msparapa** [comment]
It's not active though with their C=0.8. I tried with drag max = 0.5 and here's what I got. Thrust is essentially off but we're still gaining velocity and losing mass. Making epsilon, not so small, changest the thrust history a lot and I can sort of see the curve from BOCOP's solution, but velocity and mass don't change.

epsilon = 0.001

![thrust](https://user-images.githubusercontent.com/9142820/56460797-8b8bda80-6376-11e9-938c-d36af117ea30.png)
![mass](https://user-images.githubusercontent.com/9142820/56460799-8e86cb00-6376-11e9-8503-cc0b5621dbb6.png)
![constrained](https://user-images.githubusercontent.com/9142820/56460780-57b0b500-6376-11e9-86a0-9cd2d50fce47.png)

**Comment by msparapa** [comment]
And here's eps = 0.005. The other plots are pretty much identical.

![thrust2](https://user-images.githubusercontent.com/9142820/56460833-005f1480-6377-11e9-8fb0-612ebe6c999d.png)

**Comment by SeanMatthewNolan** [comment]
Check the final altitude. See which is optimal.

**Comment by msparapa** [comment]
Same for both. The velocity is integrated correctly but I don't think it's representing the singular arc correctly. Changing epsilon also changes thrust, but not velocity. I honestly have no idea where the problem is.

**Comment by SeanMatthewNolan** [comment]
No, it isn't. There shouldn't be a singular arc here. If they show a singular arc, it's either a difference in the numbers or they are incorrect. With epsilon as low as possible, a greater altitude is achieved. The difference isn't large because everything is normalized by the radius of the Earth, but the difference is there. Mathematically, epsilon being smaller will approach the original problem and result in a lower cost. I think if the problem is posed without the normalization, it would show the difference even clearer.
![Altitude vs Epsilon](https://user-images.githubusercontent.com/32470152/56461071-45cd1300-6372-11e9-9a3e-259283b50758.png)

**Comment by msparapa** [comment]
Maybe I'm not understanding the problem. Why does velocity increase between 0.025 and 0.075 if thrust is off?

![t-v](https://user-images.githubusercontent.com/9142820/56461148-f4298600-637b-11e9-8cbb-92e6091eff0c.png)

**Comment by msparapa** [comment]
I figured it out. It's our old friend scaling. Running with `autoscale=False` gives more reasonable answers for thrust, save for the singular arc.

**Comment by SeanMatthewNolan** [comment]
I was going to say, that the problem wouldn't be the epsilon. It had to be something else.

**Comment by msparapa** [comment]
Pretty confident this is a larger issue dealing with scaling, maybe even the math behind epsilon-trig. I think the issues here are the same that are preventing me from solving constrained hypersonic problems. Otherwise Goddard seems to be working fine. Should we close this and make a new issue to fix this?

**Comment by SeanMatthewNolan** [comment]
The scaling should be turned off in that the problem is already scaled. I was going to add some sub problems, but that is so low on my list that I'll close this now.
