### ISSUE TITLE
Organize examples into subfolders

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#193]
We have a lot of examples now. The "01", "02", etc naming convention seemed better when I started, but now I think we should organize similar examples into subfolders. Eg. we have two different launch vehicles so both should go into a `examples/LaunchVehicles` folder.

**Comment by SeanMatthewNolan** [comment]
Do you think it would be better to arrange problems by their actual likeness or by what they demonstrate in respect to the solver? For example, do we group all glide vehicle problems together or do we put problems that have path constraints together? I am in favor of the latter as they could serve as a series of tutorials.

**Comment by msparapa** [comment]
I was thinking about grouping by discipline. So like:

- Ascent Vehicles
    - Goddard Rocket
    - Titan II
    - BFR

- Electronics
    - One-Loop Circuit

- Hypersonic Flight
    - Space Shuttle Crossrange
    - Max Range

- Finance
    - Financial Oscillator

or whatever categories make sense. I don't think the average user browsing this repo is going to care about some of the gritty details involving path constraints or index reduction and what not. What's more likely is they do something totally unrelated, like circuit design, and after a quick glance they might decide this repo doesn't offer them anything because it appears to be all aero related. That said, in my mind, the `/examples/` folder would have a `README.rst` that reads more like the tutorial you suggested. That readme would have sections like

- Bang-Bang Control
    - Financial Oscillator

- Singular Arcs
    - Goddard Rocket

with links to each of the specific problems where those classical control issues come up and show how we handle it.

**Comment by SeanMatthewNolan** [comment]
After reading what you wrote and a little thought, I agree. For the tutorial stuff I have to put together anyway, I may write examples, and upload them, but I'll probably group them together to match if that's ok.

**Comment by msparapa** [comment]
Perfect dude! I started this, but didn't like how empty the examples folder seemed to have become. I guess that's the point though. We have a better organization and more room for examples.
