### ISSUE TITLE
Add support for second derivative of custom functions

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#204]
I just noticed this problem. If we have custom functions that are functions of the control variable, not only do you need the first derivative when constructing the EOMs, but also the second derivative when constructing the index reduced control EOMs. The logic I initially built didn't take this into account and it's fairly broken.

**Comment by SeanMatthewNolan** [comment]
This is handled in latest updates using numerical derivatives.
