### ISSUE TITLE
States (y) and costates (dual) are stored in different order

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#205]
This is a minor problem, but the indexing for the returned solution for the states is different than for the costates. They should be the same for consistency. The states are stored such that the time step index is second. The costates (dual) has the time step index first.

**Comment by msparapa** [comment]
Are you positive? For all the examples, time index is first on the states and costates.

**Comment by SeanMatthewNolan** [comment]
Sorry, I'm not. I meant to delete this soon after I posted it. I thought I encountered it when pulling values using the terminal. I even thought I checked it before posting, but after I posted, I saw I was wrong. I still don't know how I got so confused. I intended to delete this issue, but got distracted or something.
