### ISSUE TITLE
Add support for spline table methods

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#214]
I thought this was already an issue, but I guess not. I have been working on making a method that incorporates tables into Beluga with minimal user effort. It should appear in the input file like `ocp.table1d(name, x_data, y_data)`. I have already work almost all the technical issues I have been having. I practically just need to add the pieces to optimlib and the new codegen #206. The way that it works should make #204 fairly straightforward to address as the implementation allows the tables to be differentiated any number of times. We can generalize the structure to generic functions.

**Comment by msparapa** [comment]
In JT Bett's book, he has an example of a supersonic minimum time to climb problem. It uses a table for engine thrust data. Can you also implement that as an example? Then we can use it as an example to test the table methods.

**Comment by SeanMatthewNolan** [comment]
The large merge to resolve #216 includes support for 1D splines.
