### ISSUE TITLE
Streamline and simplify data transfer from OCP to BVP to codegen

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#216]
As far as I can tell, data, such as state equations, is first stored as strings attached as properties of the OCP. Then packed into a dictionary to be passed to the BVP that turns them into symbols to perform the symbolic math. The expressions are then turned back into strings and packed into another dictionary. Branch 206 (#206, #214, #204 ) needs the symbolic expressions for codegen, so currently another symbolic representation of the BVP is formed from the dictionary of strings, so that a "functional" BVP can be compiled. This chain is making it difficult to elegantly complete and push Branch 206. I proposed that the OCP converts all strings to symbols, which are passed to the BVP from which a functional BVP is formed in codegen

**Comment by msparapa** [comment]
Yep. As long as we can compile the BVP just fine, I'm OK with converting to symbols and never looking back at strings.

**Comment by SeanMatthewNolan** [comment]
I finally merged this into the master branch. Though everything isn't perfect, I think it is a big improvement.
