### ISSUE TITLE
SymPy 1.1+ has trouble solving some control laws

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#40]
I noticed with sympy 1.1 and 1.1.1 that the hypersonic 3 dof algebraic control laws never seem to solve. They solve after some time with 1.0 though. We probably won't need to solve these algebraically if ICRM works consistently enough. Sympy 1.1+ supports multi tangent vector fields but 1.0 doesn't. If need be we can downgrade to 1.0 and use multi cotangent vector fields and a few fancy morphisms to get around this.

**Comment by SeanMatthewNolan** [comment]
I have noticed this, but I didn't connect it to SymPy 1.1. I think it gets hung up trying to check the various edge cases and attempting to simplify the answer. I was able to get the 3dof control law to solve in a reasonable time by using the arguments simplify=False and minimal=True.

**Comment by msparapa** [comment]
Huh... We might need to come up with an example where 1.0 worked and 1.1+ hangs and submit an issue to the SymPy bros.

I could also code the multi tangent vector field operations directly into our solver, but the code would be out of place. It belongs in sympy and not here.
