### ISSUE TITLE
Remove sol.aux = solinit.aux line at end Shooting.py

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#50]
The solver fails if this seemingly pointless line is removed because the scaling (I believe) is set to modify the same object before and after the solver converges (i.e. sol = solinit, not sol = copy.deepcopy(solinit)). That the solver makes a copy of the solinit object instead of modifying it causes the aux variables to be not to be unscaled and thus scaled multiple times and making it break the solver. To work with a copy, the unscale (and scale to match) probably need to be changed to return the unscaled/scale solution instead of modifying the object.

**Comment by msparapa** [comment]
Good call I didn't even think the scaling would be the issue in this scenario. It seems like the scaling class stores references of the problem, but it probably should just use a copy of the problem and act more like a function rather than a class.
