### ISSUE TITLE
Fix plotting tools for new handling of tf

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#52]
Plotting time is broken with appending tf to the parameters instead of states

**Comment by msparapa** [comment]
Should be an easy fix. I'm having solver solver output the x-axis in proper scaling now as opposed to [0,1], so the visualization package will probably just need the hardcoding removed.

**Comment by SeanMatthewNolan** [comment]
I think I already fixed it. I put it here to reference for history.

**Comment by SeanMatthewNolan** [comment]
I'll commit it soon with a working 3dof problem.
