### ISSUE TITLE
Remove simple pipe from optimlib

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#55]
This appears just to obfuscates the code with no real benefit.

**Comment by msparapa** [comment]
I talked to both thomas and prof grant about this a bit and still have mixed feelings. A subtask here would be to first create a similar composable workflow, mimicking that like I set up in branch I42 #42, in pure Python. It should be able to do this without any issue, but as of the latest commit in I42, ICRM and Bryson and Ho share code so we should close out #42 before tackling this.

**Comment by SeanMatthewNolan** [comment]
Originally, I meant to reference #42 in the description but got distracted while typing. In my mind, I saw this as a "sub" issue. I just put this up here because I was looking at it. I wasn't actively going to work on it without working on #42.

**Comment by msparapa** [comment]
I noticed in #57 that, even though most of the data was contained within `simplepipe`, it affected data outside of that scope because of pointers and such.
