### ISSUE TITLE
Get custom functions working again

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#56]
I may have done it incorrectly, but when I tried it out just now I don't think our solver handles custom functions anymore. We'll need to build this feature into some parseexpression() method, which then everything else calls (quantities, state eoms, boundary conditions, etc). Then we can have custom functions anywhere in the problem.

**Comment by msparapa** [comment]
@SeanMatthewNolan Can you take a look at branch I56? Run the brachistochrone problem with the way I have it set up and the code should `keyboard()` out in `beluga/codegen/codegen.py` on line 176. I've been trying to get the `eval()` function to register that there is a custom function called `custom_cosine()` but I haven't quite figured out how. This is really puzzling to me since it knows all the standard `math` commands from the import statement on line 17, and it also knows imaginary from line 18, but I can't seem to get it to tell that there are other functions defined.

I think the key here is to get `eval()` to correctly evaluate the statement, then using Numba should be good to go. If you're able to fix this then go ahead and push a commit on the branch, then I can implement it w/ `OCP` and merge this feature back in to master.

**Comment by SeanMatthewNolan** [comment]
@msparapa Sorry for not replying earlier, would you still like me to look at the custom functions or are we set now?

**Comment by msparapa** [comment]
I think we are good. I made a new issue for outputting dill data files in #96.

If you still want to peruse through my changes that would be fine. I don't think I implemented this in the "best" way.
