### ISSUE TITLE
Follow a better standard for boundary condition inputs

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#64]
Right now we use

`(y0, yf, parameters, aux)`

but this is fairly different than most bvp solvers. We should change the general standard to

`(t0, y0, q0, tf, yf, qf, parameters, aux)`

It's more terms, but makes less assumptions about the type of boundary conditions used.

**Comment by SeanMatthewNolan** [comment]
I agree, but what is q? Are those the boundary conditions?

**Comment by msparapa** [comment]
Initial and terminal points of the quads from my research. We don't have any examples that use them right now, but my current work shows that they are a unique parts of a dynamical system. You'll see in the bvp solver `quad_func` is an input, but we pretty much assume it's always `None`. They're placeholders for now to make it easier for me to program in at a later time.
