### ISSUE TITLE
Delete unnecessary and large files

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#7]
How is our solver 1.1gb? lol there's no way

**Comment by SeanMatthewNolan** [comment]
Based on my quick looking through, I think much of that is from .dill files.

**Comment by msparapa** [comment]
I purged the git history or all .dill, .pkl, and other files. You'll need to reclone the repository.

For some reason it didn't clear .mat files or .gif files. We're down to 30mb total so I'm going to call this a success.
