### ISSUE TITLE
Missing variable in Solution.py line 134 (self.parameters)

### ISSUE THREAD

**Issue by kresso** [Rapid-Design-of-Systems-Laboratory/beluga#73]
I was getting this error when calling Solution.py

Traceback (most recent call last):

  File "<ipython-input-11-abc66286da86>", line 3, in <module>
    sol.prepare(out_not_sanitized['problem_data'])

  File "\Continuum\anaconda3\lib\site-packages\beluga\bvpsol\Solution.py", line 134, in prepare
    t, y, u, p, arcs = new_t, new_y, new_u, new_arcs

ValueError: not enough values to unpack (expected 5, got 4)

On line 134 there are 5 variables trying to write to 4 variables. I fixed it locally and it seems to work. Is there somewhere I should post bugs?
t, y, u, p, arcs = new_t, new_y, new_u, new_arcs    ->
t, y, u, p, arcs = new_t, new_y, new_u, self.parameters, new_arcs

**Comment by msparapa** [comment]
Posting bugs here is fine! Yeah that doesn't look right. What were you trying to run? I'm not entirely certain what this block of code is used for in the first place.

**Comment by SeanMatthewNolan** [comment]
@msparapa I wasn't sure what the intent of the code was at first, but I think I figured it out at least in that context. With that said, I think I fixed it (deleted p on the lhs), but I just needed to generate data to verify that it is fixed before pushing it.

**Comment by msparapa** [comment]
Is it for interpolation? I wrote a section in `Trajectory()` that handles interpolation when you call an ivp solution as if its a function, rather than a data structure. I then subclassed `Solution()` from `Trajectory()`, but didn't go through `Solution()` in detail. It might be worth rewriting `Solution()` altogether.

**Comment by SeanMatthewNolan** [comment]
Yes, it probably should be removed, but I'll push this simple fix now.
