### ISSUE TITLE
Rewrite Solution()

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#74]
As per discussion in #73, I think there's some useless code in `Solution()`. We should comb through it.

**Comment by msparapa** [comment]
@SeanMatthewNolan can I just axe `Solution` from `bvpsol` altogether and have every trajectory just be represented by `Trajectory` in `ivpsol`? This will break `visualization` functionality, but I can modify the output of beluga to return the entire continuation so all the data is still there. `Solution` is really clunky and it is doing stuff that shouldn't be located there.

**Comment by SeanMatthewNolan** [comment]
@msparapa That sounds fine with me. They do seem redundant. Visualization needs to be redone regardless, so it may force us to do so.
