### ISSUE TITLE
Prevent beluga from "setting up" multiple times

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#76]
This one's a little hard to explain. Add

```
beluga.setup_beluga(logging_level=logging.DEBUG)
beluga.setup_beluga(logging_level=logging.DEBUG)
beluga.setup_beluga(logging_level=logging.DEBUG)
```

to any problem x20 then let it rip. It seems like it's using multiple loggers. I think simply clearing any old parameters whenever `setup_beluga()` is called should be sufficient to fix this issue.

**Comment by msparapa** [comment]
I think this is actually expected behavior. After looking at how our logger is set up, each time `setup_beluga()` is run, it appends a logging stream. So theoretically there could be multiple output streams to different files and such.

**Comment by SeanMatthewNolan** [comment]
This may be missing the point, but instead of running setup_beluga twice, would it be better to run some derivative method or modify it to take an argument of a previous problem?

**Comment by msparapa** [comment]
I think having `setup_beluga()` in the past made sense since we needed to locate a Mathematica installation, but since we use SymPy, all it does now it set up the logging and output files. Maybe renaming this function would be clearer. Break it up into a `add_logger()` and `set_output_file()`.

Then, as you said, we should probably have some feature where it can accept info saved from a previous problem. The initial guess can already accept the previous solution well enough, but we probably should also add a feature where we can input an already defined problem along with its compiled code.
