### ISSUE TITLE
Add Python 3.7 support

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#84]
Conda with python 3.7 isn't out yet, but when it is released, we'll need to upgrade and also maintain compatibility with 3.5 and 3.6.

**Comment by SeanMatthewNolan** [comment]
@msparapa Why do we use Anaconda? Everything works fine without it.

**Comment by msparapa** [comment]
That's a good point. I think we used to used to get the accelerate edition for free as students, but that's no longer around. I think we just stick with anaconda python since it's pretty standard in the scientific community.

Maybe changing instructions to use just Python would be better in this case.

**Comment by SeanMatthewNolan** [comment]
I think it would be. I don't see specifying that adding any additional capability for us.
