### ISSUE TITLE
Add actual Armijo Line-search

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#89]
This has been seen as an optional feature in the past, but my experience with a custom solver makes me believe that a line-search significantly improves robustness and speed, so I am going to add this as soon as I get back to Purdue.

**Comment by SeanMatthewNolan** [comment]
This is functionally done on branch I97.

**Comment by msparapa** [comment]
I'll probably break up some of your work into different branches to make it easier to merge back into master without breaking anything.

**Comment by SeanMatthewNolan** [comment]
I added this in the ShootingArmijo algorithm. Ultimately, this should probably replace Shooting, but enough has changed within it that keeping both for testing is probably wise.

**Comment by msparapa** [comment]
Gotcha. I'll keep that in mind as I try to implement #47
