### ISSUE TITLE
Make bvp solver accept preloaded functions

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#97]
Continuing discussion from #22, whatever way we implement our bvp solver, it needs to accept "preloaded" equations of motion and function files to lessen the overhead caused by passing around functions and calling jit(). It also needs to retain the "standard" engineering-style interface that typical bvp solvers use today.

We could implement two solutions, I97A and I97B, then we can discuss.

**Comment by SeanMatthewNolan** [comment]
I sort of wrote a "third-way" solution with a `load_problem_info` method. This is not as elegant as I'd like, but is to fit into the order beluga generates the objects and has information available to use.

**Comment by msparapa** [comment]
I get why you did it this way now. I want each of the modules (bvpsol, ivpsol, etc) to all work independently of one another. i.e. bvpsol shouldn't require inputs from some other module within beluga, it should just accept inputs in a standard format, then the code within beluga wrapped around bvpsol should adhere to what bvpsol is doing. Since we are creating the objects themselves in the input files, but ode's and bc's are generated after the code has been running, it doesn't have the required data at input file time.

It might be better to curry the inputs. I'm trying this in `I97b`.

**Comment by SeanMatthewNolan** [comment]
Yeah, it took me a little to see that that was what you were trying to do. I think it comes down to what is decided to be more important, but I think we are going to take a significant performance hit if we don't pre-load functions. Honestly, I am not a huge fan of what I think your work around is for reasons that are probably easier to discuss in person, but I may be wrong. If it is important to have versions that operate outside, it would be as easy as 

`def solve(deriv_func, quad_func, bc_func, solinit, cont_values, *args)
    return bvp_algo(deriv_func, quad_func, bc_func, *args).solve_in_beluga(solinit, cont_values)`

**Comment by msparapa** [comment]
Added this into master. I'm leaving your branch I97 open because it has useful stuff for #89.
