### ISSUE TITLE
Independent variable is never used as an input in the ode and bc funcs

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#98]
Try setting up a problem with time in one of the eoms. Our compiler can't handle it because time isn't listed as an argument

**Comment by msparapa** [comment]
With the implementation of #124, #126, #111, etc... I think we can handle time effectively as an extra state now as opposed to a true independent variable. For cases where D_(H)/D_t != 0, time is a state and problems where D_(H)/D_t = 0, we can handle time as a quad. This will reduce the boundary condition arguments down from

```
bc(t0, y0, q0, u0, tf, yf, qf, uf, params, ndp, aux)
```
to
```
bc(y0, q0, u0, yf, qf, uf, params, ndp, aux)
```

We don't currently use `t0` and `tf` anyways so the current set up is misleading. This is also much closer to `bvp4c`'s argument set up.

**Comment by msparapa** [comment]
Partially fixed. Closing because this is a part of a bigger issue than described here.

**Comment by SeanMatthewNolan** [comment]
@msparapa Does the bigger issue have an actual "issue" opened?

**Comment by msparapa** [comment]
Coulda sworn we did, but I checked and I guess not. I got ahead of myself after titan II converged.

**Comment by msparapa** [comment]
@SeanMatthewNolan Heads up on closing this issue and releasing 0.3.2: Internally, time always gets adjoined as a state. So for 0.3.2 onwards, you will actually need to write `t-0` as an initial constraint. This is much more generalized. I'm pretty confident you can include time in the equations of motion now. Also, I kept the final time dynamical parameter, which effectively represents total time. It seems sort of silly to have a state and a parameter to both handle time, but the dynamical parameter is for scaling and the state is for use in EOMs. Because everything is adjoined, the BCs are super generalized but we still have the automatic scaling with `tf`. I haven't run into any problems with our existing examples. In fact, this simplified the financial oscillator somewhat.
